### ISSUE TITLE
config.w32 is missing from PECL package (0.9.3)

### ISSUE THREAD

**Issue by cmb69** [supermetrics-public/pecl-jsonpath#135]
Although config.w32 is part of the repository, for some reason it is missing from the PECL package jsonpath-0.9.3.tgz; that prevents the Windows DLLs to be build on the PECL build machine.

**Comment by crocodele** [comment]
Thanks, I'll look into it. I'm new to building PEAR packages, so I might have missed something in the packaging steps.

**Comment by cmb69** [comment]
Ah, it's missing from package.xml, although [config.m4](https://github.com/supermetrics-public/pecl-jsonpath/blob/main/package.xml#L30) is there.
