### ISSUE TITLE
Windows prebuild DLLs

### ISSUE THREAD

**Issue by macintoshplus** [supermetrics-public/pecl-jsonpath#178]
Hi,

I have initiated a CI to build some PHP extensions for Windows.

This extension is now available here: https://phpext.phptools.online/extension/tools-and-utilities/jsonpath-308

I'm available for more information.

**Comment by crocodele** [comment]
@macintoshplus, sounds good! A couple of questions:

1. Do you automatically build new versions as well?
2. Can you fix the list of maintainers please? It should be Viktor Djupsjöbacka (lead) and Mike Kaminski (lead).

**Comment by macintoshplus** [comment]
Thanks @crocodele 

> Do you automatically add new versions as well?

Yes, I get the new versions and new PHP Extensions from PECL website.

> Can you fix the list of maintainers please? It should be Viktor Djupsjöbacka (lead) and Mike Kaminski (lead).

I copied this information from the "package.xml" file from the extension release archive uploaded on PECL website.
On the next version, add the new lead in this file. It will be added to PHP Repository Extension website.

Otherwise, I have an idea to make a web form to help apply change into a "package.xml" file. Does that interest you?

**Comment by crocodele** [comment]
> > Can you fix the list of maintainers please? It should be Viktor Djupsjöbacka (lead) and Mike Kaminski (lead).
> 
> I copied this information from the "package.xml" file from the extension release archive uploaded on PECL website. On the next version, add the new lead in this file. It will be added to PHP Repository Extension website.

@macintoshplus, can you double-check this please? There's no mention of Pierre Joye in the whole history of jsonpath's [package.xml](https://github.com/supermetrics-public/pecl-jsonpath/blob/main/package.xml). And Mike Kaminski has been there since version 0.9.4.
 
> Otherwise, I have an idea to make a web form to help apply change into a "package.xml" file. Does that interest you?

Automated from latest release is better IMHO. :slightly_smiling_face:

**Comment by macintoshplus** [comment]
> @macintoshplus, can you double-check this please? There's no mention of Pierre Joye in the whole history of jsonpath's [package.xml](https://github.com/supermetrics-public/pecl-jsonpath/blob/main/package.xml). And Mike Kaminski has been there since version 0.9.4.

I have found the issue. 'Mike Kaminski' doesn't have an email in the package.xml file.
When I import the package.xml file, I search the maintainer by email to deduplicate the maintainer.
I have fixe the problem for jsonpath.

> > Otherwise, I have an idea to make a web form to help apply change into a "package.xml" file. Does that interest you?
>
> Automated from latest release is better IMHO. 🙂

Yes or from external XML for existing extensions and empty form for new extensions.

**Comment by crocodele** [comment]
Thank you, @macintoshplus. I've added a link in the README, in the Installation section. :slightly_smiling_face:
